# Generated by Django 5.1.2 on 2024-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_emergencydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydetails',
            name='urgency_level',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Within 24 hours', 'Within 24 hours'), ('Within 3 days', 'Within 3 days')], default='Immediate', max_length=100),
        ),
    ]
