# Generated by Django 5.1.2 on 2024-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_emergencydetails_urgency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydetails',
            name='units_needed',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
