# Generated by Django 5.1.2 on 2024-12-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_emergencydetails_units_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencydetails',
            name='hospital_name',
            field=models.CharField(max_length=300),
        ),
    ]
